### PR TITLE
Request: fixed return typehint

### PR DESCRIPTION
**Pull request by pepakriz**
Introduced in https://github.com/nette/http/commit/28af265b9c5393eb344ac82cbc7a41facee9eeee

### CODE REVIEW

**Comment by dg** [comment]
Can you explain it?

**Comment by dg** [comment]
@coveralls do not spam my repos, bitch.

**Comment by hrach** [comment]
It's one click setup in your coveralls profile. Sadly, this is the default.

**Comment by dg** [comment]
When you press "Save changes", it is again enabled.

**Pull request merged**
