### PR TITLE
Configurable name of cookie browserKey

### PR DESCRIPTION
**Pull request by jasin755**

### CODE REVIEW

**Comment by JanTvrdik** [comment]
It breaks tests. You cannot use `$options` like that.

**Comment by jasin755** [comment]
What is the correct way?

**Comment by Unlink** [comment]
I think, you should add new field for that and sets it in `SessionExtension`.
`$options` are used for [php session variables](https://php.net/manual/en/session.configuration.php)

**Comment by dg** [comment]
I think that configurable name is needless complexity, better is to use constant.

**Comment by jasin755** [comment]
Occasionally are found clients who for some reason refuses to show what framework is used. There is no way (except hack) how to accommodate them.

**Comment by dg** [comment]
Closed by #103

**Pull request closed without merging**
