### PR TITLE
IResponse: added HTTP response codes from accepted RFC 6585

### PR DESCRIPTION
**Pull request by matyx**
RFC: https://tools.ietf.org/html/rfc6585

### CODE REVIEW

**Comment by dg** [comment]
Do you think this is useful?

**Comment by matyx** [comment]
@fprochazka Yes, I will add them.
@dg I need only 429 - Too many requests (for API). I added all from the RFC only because of completness

**Comment by fprochazka** [comment]
@dg it's better to have those codes as constants. And it's weird to have half defined in nette and half in custom class.

**Comment by Majkl578** [comment]
There is even more codes missing here, see Symfony's Response constants: https://github.com/symfony/symfony/blob/c0a26bc/src/Symfony/Component/HttpFoundation/Response.php#L21-L82

**Comment by matyx** [comment]
I've added all missing response codes

**Comment by rostenkowski** [comment]
:tophat:

**Comment by rostenkowski** [comment]
As for community-driven development this a good pull request!

:+1:

**Comment by fprochazka** [comment]
@matyx awesome :+1:

**Pull request merged**
