### PR TITLE
IRequest::getServerParameters()

### LINKED ISSUE #166: Request - server parameters
I am missing abstraction for `$_SERVER` in request. I would like to have `IRequest->getServerParameters()`. Should I send a PR?

### PR DESCRIPTION
**Pull request by mabar**
- new feature? yes
- BC break? yes

Closes #166

### CODE REVIEW

**Comment by dg** [comment]
Server parameters really are not part of HTTP request…

**Comment by mabar** [comment]
Not all, but many of them are request-specific, like `HTTP_USER_AGENT` and `REQUEST_METHOD`. Initially I created this PR and related issue because PSR-7 include `getServerParams()` too and in `ServerRequestInterface` docs is statement `$_SERVER values represent application state at the time of request` which sounds reasonable to me. But I see your point of view now. Would an addition of specific methods like `getHttpAgent()` be more acceptable?

**Comment by dg** [comment]
Why you dont like getHeader('User-Agent') ?

**Comment by mabar** [comment]
Nevermind, bad example. It was all about variable abstraction. But it does not belong to request as you pointed, so I may just create separate object for that

**Pull request closed without merging**
