### PR TITLE
UrlScript: added getAppPath()

### PR DESCRIPTION
**Pull request by JanTvrdik**
When implementing custom router you usually need this method. The algorithm was taken from https://github.com/nextras/static-router/blob/d97be13214443e03cc5efb849adc69d9ae0a2a5d/src/StaticRouter.php#L49 and it should be equivalent what Route [is doing](https://github.com/nette/application/blob/2d1e6b9880a3b375ce65df57ca3715850b6c0ecc/src/Application/Routers/Route.php#L162-L166) (just micro-optimized). Although I think I made some assumption which I'm not sure if they are generally true. However the idea is important, the algorithm could be polished.

Thoughts?

### CODE REVIEW

**Comment by dg** [comment]
How does it differ from getPathInfo()?

**Comment by JanTvrdik** [comment]
Added a test which explains the difference. See also https://github.com/nextras/static-router/commit/5a137d9a6ff1a8871224ba2710864a3e19933638

**Comment by dg** [comment]
Hmm, what about name? `getAppPath()` sound that it returns the exactly other part of path, or isn't it?

**Comment by JanTvrdik** [comment]
Well I guess it is a but ambiguous. The idea is the router basically transforms *appPath*  to *appRequest*.

**Comment by JanTvrdik** [comment]
This is still a very good idea. Suggestions for better method name are appreciated.

**Comment by JanTvrdik** [comment]
I still need this and I still don't have a better name.

**Comment by milo** [comment]
Something like variablePath or variableUrl? It is the part of url which is changing.

**Comment by f3l1x** [comment]
Alternatives:
- appPath (8/10)
- variablePath (5/10)
- slugPath (2/10)

It might be helpful in the future. Any progress here?

**Comment by dg** [comment]
I will use relativePath.

**Pull request closed without merging**
