### PR TITLE
Feature: Missing FileUpload::isEmpty()

### PR DESCRIPTION
**Pull request by JanTvrdik**
How do you feel about adding `isEmpty()` shortcut to `FileUpload`
defined as `$this->error === UPLOAD_ERR_NO_FILE`?

### CODE REVIEW

**Comment by JanTvrdik** [comment]
Converted to PR

**Comment by Majkl578** [comment]
I thought this is about checking whether the uploaded file is empty, until I read the description... So the name is confusing name imho.

**Comment by hrach** [comment]
What about isFilled()?

**Comment by SlavaAurim** [comment]
Maybe `noFile()` (like constant name `UPLOAD_ERR_NO_FILE`)

**Comment by Majkl578** [comment]
More options:
* hasFile()
* hasNoFile()
* isFileMissing()
* isFilePresent()
* fileExists()

**Comment by dg** [comment]
`hasFile()` seems perfect to me.

**Comment by dg** [comment]
Thanks

**Pull request merged**
