### PR TITLE
HttpExtension: allow setup CSP in restrictive and report mode at the …

### PR DESCRIPTION
**Pull request by PavelJurasek**
…same time

Solution for both modes of CSP.
Related to https://github.com/nette/http/pull/135.

### CODE REVIEW

**Comment by PavelJurasek** [comment]
@spaze Do you think it's OK to use the same nonce for CSP and CSP-ReportOnly headers?

**Comment by dg** [comment]
Thanks!

**Comment by PavelJurasek** [comment]
I thank you! 🙏 
I'll be happy to see new release as it has been over 6 months since last release.

**Comment by dg** [comment]
I picked it in 2.4 too

**Comment by spaze** [comment]
@PavelJurasek 
>Do you think it's OK to use the same nonce for CSP and CSP-ReportOnly headers?

It is. Also, nice addition, although `csp-report` might be a bit misleading, I'd suggest `csp-report-only` or something but it's probably too late.

**Comment by dg** [comment]
I have changed option to `cspReportOnly` to be consistent with the rest of configuration.

**Pull request closed without merging**
